# You are given two strings, str_1 and str_2, where str_2 is generated by randomly suffling str_1 and then adding one letter at the random position

# Write a function that returns the letter that was add to str_2

def csFindAddedLetter(str_1, str_2):

    '''
    We use a for loop to go through the day, then compare str_1
    to str_2. This comparison counts the occurance of each letter
    , and from that determines which string is longer.
    '''

    for i in str_2:
        if str_2.count(i) != str_1.count(i):
            return i


str_1 = "bcde"
str_2 = "bcdef"
print(csFindAddedLetter(str_1, str_2))